// Copyright 2026 Andre Cipriani Bandarra
// SPDX-License-Identifier: Apache-2.0

use std::sync::Arc;

use futures_util::{Stream, StreamExt};
use serde::de::DeserializeOwned;
use tracing::{debug, instrument};

use crate::{
    agent::Agent,
    error::Error,
    model::{LlmModel, Message, ModelRequest, ModelStreamChunk, ToolCall},
    tool::ToolRegistry,
};

/// The result of a completed agent run.
#[derive(Debug, Clone)]
pub struct AgentResult {
    /// The final text output produced by the agent.
    pub output: String,
}

/// An observable event emitted by [`AgentRunner::run_stream`] during an agent run.
///
/// Tool call lifecycle events (`ToolCallStarted`, `ToolCallCompleted`) are
/// generated by the runner. `Thinking` and `TextDelta` are forwarded directly
/// from the model's stream.
#[derive(Debug, Clone)]
pub enum AgentEvent {
    /// The model requested a tool call. Emitted before the tool executes.
    ToolCallStarted {
        /// The name of the tool being invoked.
        name: String,
        /// The arguments the model wants to pass, as a JSON object.
        args: serde_json::Value,
    },
    /// A tool call completed. Emitted after the tool returns.
    ToolCallCompleted {
        /// The name of the tool that was invoked.
        name: String,
        /// The value returned by the tool.
        result: serde_json::Value,
    },
    /// A reasoning/thinking token from a model that supports extended thinking.
    Thinking(String),
    /// An incremental chunk of the model's final text response.
    TextDelta(String),
}

/// Executes [`Agent`]s against an LLM model.
///
/// `AgentRunner` owns the model and holds a reference to a [`ToolRegistry`].
/// The same runner can execute multiple agents; a [`ToolRegistry`] can be
/// shared across multiple runners via [`Arc`].
///
/// For single-turn use, call [`run`], [`run_typed`], or [`run_stream`] directly.
/// For multi-turn conversations, use [`run_builder`] to obtain a [`RunBuilder`]
/// and supply the prior conversation history via [`RunBuilder::history`].
///
/// # Examples
///
/// ```no_run,ignore
/// use agent_rig::{Agent, AgentRunner};
/// use agent_rig::models::gemini::GeminiModel;
///
/// # #[tokio::main]
/// # async fn main() -> Result<(), Box<dyn std::error::Error>> {
/// let model = GeminiModel::builder("API_KEY", "gemini-2.5-pro-preview-03-25")
///     .temperature(0.8)
///     .build();
///
/// let agent = Agent::builder()
///     .name("Assistant")
///     .instructions("You are a helpful assistant.")
///     .build();
///
/// let runner = AgentRunner::new(Box::new(model));
/// let result = runner.run(&agent, "Hello!").await?;
/// println!("{}", result.output);
/// # Ok(())
/// # }
/// ```
///
/// [`run`]: AgentRunner::run
/// [`run_typed`]: AgentRunner::run_typed
/// [`run_stream`]: AgentRunner::run_stream
/// [`run_builder`]: AgentRunner::run_builder
pub struct AgentRunner {
    model: Box<dyn LlmModel>,
    registry: Arc<ToolRegistry>,
}

impl AgentRunner {
    /// Creates a new `AgentRunner` powered by the given model with an empty
    /// tool registry. Suitable for agents that use no tools.
    pub fn new(model: Box<dyn LlmModel>) -> Self {
        AgentRunner {
            model,
            registry: ToolRegistry::empty(),
        }
    }

    /// Creates a new `AgentRunner` powered by the given model and sharing the
    /// given [`ToolRegistry`].
    ///
    /// Multiple runners can share the same registry by passing [`Arc::clone`]
    /// of the same instance.
    pub fn with_registry(model: Box<dyn LlmModel>, registry: Arc<ToolRegistry>) -> Self {
        AgentRunner { model, registry }
    }

    /// Returns a [`RunBuilder`] for the given agent, enabling optional
    /// conversation history to be provided before execution.
    ///
    /// Use this when you need multi-turn dialogue: supply prior turns via
    /// [`RunBuilder::history`], then call one of the execution methods
    /// ([`run`], [`run_typed`], [`run_stream`]) on the builder.
    ///
    /// For single-turn use, calling [`AgentRunner::run`] directly is simpler.
    ///
    /// # Examples
    ///
    /// ```no_run,ignore
    /// use agent_rig::{Agent, AgentRunner};
    /// use agent_rig::model::Message;
    /// use agent_rig::models::gemini::GeminiModel;
    ///
    /// # #[tokio::main]
    /// # async fn main() -> Result<(), Box<dyn std::error::Error>> {
    /// let model = GeminiModel::builder("API_KEY", "gemini-2.5-pro-preview-03-25").build();
    /// let agent = Agent::builder()
    ///     .name("Assistant")
    ///     .instructions("You are a helpful assistant.")
    ///     .build();
    /// let runner = AgentRunner::new(Box::new(model));
    ///
    /// // First turn.
    /// let first = runner.run(&agent, "My name is Alice.").await?;
    ///
    /// // Build history for the second turn.
    /// let history = vec![
    ///     Message::user("My name is Alice."),
    ///     Message::assistant(&first.output),
    /// ];
    ///
    /// let second = runner
    ///     .run_builder(&agent)
    ///     .history(history)
    ///     .run("What is my name?")
    ///     .await?;
    ///
    /// println!("{}", second.output); // "Alice"
    /// # Ok(())
    /// # }
    /// ```
    ///
    /// [`run`]: RunBuilder::run
    /// [`run_typed`]: RunBuilder::run_typed
    /// [`run_stream`]: RunBuilder::run_stream
    pub fn run_builder<'a>(&'a self, agent: &'a Agent) -> RunBuilder<'a> {
        RunBuilder {
            runner: self,
            agent,
            history: Vec::new(),
        }
    }

    /// Streams observable events produced during an agent run.
    ///
    /// Drives the same agentic loop as [`run`] — validate tools, call the
    /// model, execute tool calls, repeat — but exposes every step as an
    /// [`AgentEvent`]:
    ///
    /// - [`AgentEvent::TextDelta`] — incremental text chunks from the model.
    /// - [`AgentEvent::Thinking`] — reasoning tokens (models that support it).
    /// - [`AgentEvent::ToolCallStarted`] — emitted before each tool executes.
    /// - [`AgentEvent::ToolCallCompleted`] — emitted after each tool returns.
    ///
    /// The stream ends when the model produces a final text response (no more
    /// tool calls). Errors are yielded as `Err` items and terminate the stream.
    ///
    /// For multi-turn conversations, use [`run_builder`] and call
    /// [`RunBuilder::run_stream`] instead.
    ///
    /// # Errors
    ///
    /// Yields [`Error::Agent`] if a tool name is unregistered, the model calls
    /// an unregistered tool, or the model returns neither text nor tool calls.
    ///
    /// [`run`]: AgentRunner::run
    /// [`run_builder`]: AgentRunner::run_builder
    /// [`RunBuilder::run_stream`]: RunBuilder::run_stream
    pub fn run_stream<'a>(
        &'a self,
        agent: &'a Agent,
        input: &'a str,
    ) -> impl Stream<Item = Result<AgentEvent, Error>> + Send + 'a {
        self.run_builder(agent).run_stream_owned(input.to_string())
    }

    /// Runs the given agent with the provided user input and returns the result.
    ///
    /// If the agent declares tools, the runner validates that every tool name
    /// is present in its registry before making any network call, then executes
    /// the agentic loop: model call → tool execution → model call, repeating
    /// until the model produces a final text response.
    ///
    /// The output is returned as a raw string. Use [`run_typed`] when the agent
    /// produces structured JSON that should be deserialized into a concrete type.
    ///
    /// For multi-turn conversations, use [`run_builder`].
    ///
    /// # Errors
    ///
    /// Returns [`Error::Agent`] if a tool name declared by the agent has no
    /// registered implementation, or if the model loop ends without a text
    /// response.
    ///
    /// [`run_typed`]: AgentRunner::run_typed
    /// [`run_builder`]: AgentRunner::run_builder
    #[instrument(skip(self, input), fields(agent = agent.name()))]
    pub async fn run(&self, agent: &Agent, input: &str) -> Result<AgentResult, Error> {
        self.run_builder(agent).run(input).await
    }

    /// Runs the given agent and deserializes the output into `T`.
    ///
    /// This is a typed convenience wrapper around [`run`]. Set `output_schema`
    /// on the agent via [`AgentBuilder::output_schema`] to constrain the model
    /// to produce JSON that matches `T`; this method handles the deserialization.
    ///
    /// For multi-turn conversations, use [`run_builder`].
    ///
    /// # Errors
    ///
    /// Returns [`Error::Agent`] if the model response cannot be deserialized
    /// into `T`.
    ///
    /// # Examples
    ///
    /// ```no_run,ignore
    /// use agent_rig::{Agent, AgentRunner};
    /// use agent_rig::models::gemini::GeminiModel;
    /// use schemars::JsonSchema;
    /// use serde::Deserialize;
    ///
    /// #[derive(Debug, Deserialize, JsonSchema)]
    /// struct Summary { headline: String, body: String }
    ///
    /// # #[tokio::main]
    /// # async fn main() -> Result<(), Box<dyn std::error::Error>> {
    /// let model = GeminiModel::builder("API_KEY", "gemini-2.5-flash").build();
    /// let schema = schemars::schema_for!(Summary);
    /// let agent = Agent::builder()
    ///     .name("Summariser")
    ///     .instructions("Summarise the text.")
    ///     .output_schema(schema)
    ///     .build();
    ///
    /// let summary: Summary = AgentRunner::new(Box::new(model))
    ///     .run_typed(&agent, "Long article text…")
    ///     .await?;
    /// println!("{}", summary.headline);
    /// # Ok(())
    /// # }
    /// ```
    ///
    /// [`run`]: AgentRunner::run
    /// [`run_builder`]: AgentRunner::run_builder
    /// [`AgentBuilder::output_schema`]: crate::AgentBuilder::output_schema
    pub async fn run_typed<T>(&self, agent: &Agent, input: &str) -> Result<T, Error>
    where
        T: DeserializeOwned,
    {
        self.run_builder(agent).run_typed(input).await
    }
}

/// A builder for a single agent execution, produced by [`AgentRunner::run_builder`].
///
/// Optionally supply prior conversation turns with [`history`] before calling
/// one of the execution methods: [`run`], [`run_typed`], or [`run_stream`].
///
/// The builder is consumed by the execution method, so each invocation needs a
/// fresh builder (call [`AgentRunner::run_builder`] again for the next turn).
///
/// [`history`]: RunBuilder::history
/// [`run`]: RunBuilder::run
/// [`run_typed`]: RunBuilder::run_typed
/// [`run_stream`]: RunBuilder::run_stream
pub struct RunBuilder<'a> {
    runner: &'a AgentRunner,
    agent: &'a Agent,
    history: Vec<Message>,
}

impl<'a> RunBuilder<'a> {
    /// Sets the prior conversation history for this run.
    ///
    /// The messages are prepended to the conversation before the new user
    /// input supplied to the execution method. The caller is responsible for
    /// maintaining and extending the history across turns.
    ///
    /// # Examples
    ///
    /// ```no_run,ignore
    /// use agent_rig::model::Message;
    /// # use agent_rig::{Agent, AgentRunner};
    /// # use agent_rig::models::gemini::GeminiModel;
    /// # #[tokio::main]
    /// # async fn main() -> Result<(), Box<dyn std::error::Error>> {
    /// # let model = GeminiModel::builder("KEY", "gemini-2.5-flash").build();
    /// # let agent = Agent::builder().name("A").instructions("i").build();
    /// # let runner = AgentRunner::new(Box::new(model));
    /// let history = vec![
    ///     Message::user("My name is Alice."),
    ///     Message::assistant("Got it, Alice!"),
    /// ];
    /// let result = runner.run_builder(&agent).history(history).run("What is my name?").await?;
    /// # Ok(())
    /// # }
    /// ```
    pub fn history(mut self, history: Vec<Message>) -> Self {
        self.history = history;
        self
    }

    /// Streams observable events produced during the agent run.
    ///
    /// Drives the agentic loop using the prior [`history`] (if set) plus the
    /// new `input` turn, yielding [`AgentEvent`] values as the run progresses.
    ///
    /// [`history`]: RunBuilder::history
    pub fn run_stream(self, input: &str) -> impl Stream<Item = Result<AgentEvent, Error>> + Send + 'a {
        self.run_stream_owned(input.to_string())
    }

    /// Runs the agent and returns the final text output.
    ///
    /// Appends `input` as a new user turn to the prior [`history`] (if set),
    /// then drives the agentic loop until the model produces a final text
    /// response.
    ///
    /// # Errors
    ///
    /// Returns [`Error::Agent`] if a tool name declared by the agent has no
    /// registered implementation, or if the model loop ends without a text
    /// response.
    ///
    /// [`history`]: RunBuilder::history
    pub async fn run(self, input: &str) -> Result<AgentResult, Error> {
        let mut output = String::new();
        let stream = self.run_stream(input);
        futures_util::pin_mut!(stream);
        while let Some(event) = stream.next().await {
            if let AgentEvent::TextDelta(chunk) = event? {
                output.push_str(&chunk);
            }
        }
        Ok(AgentResult { output })
    }

    /// Runs the agent and deserializes the output into `T`.
    ///
    /// A typed convenience wrapper around [`run`]. Deserialization failure
    /// returns [`Error::Agent`].
    ///
    /// [`run`]: RunBuilder::run
    pub async fn run_typed<T>(self, input: &str) -> Result<T, Error>
    where
        T: DeserializeOwned,
    {
        let result = self.run(input).await?;
        serde_json::from_str::<T>(&result.output)
            .map_err(|e| Error::Agent(format!("failed to deserialize structured output: {e}")))
    }

    /// Internal: takes ownership of the input string so the returned stream
    /// can be `'a` without borrowing `input` from the caller's stack frame.
    fn run_stream_owned(
        self,
        input: String,
    ) -> impl Stream<Item = Result<AgentEvent, Error>> + Send + 'a {
        let RunBuilder { runner, agent, mut history } = self;
        history.push(Message::user(input));

        async_stream::try_stream! {
            debug!(agent = agent.name(), "starting run");

            // Validate that every declared tool name is registered.
            for name in agent.tool_names() {
                if !runner.registry.contains(name) {
                    Err(Error::Agent(format!(
                        "tool '{name}' is declared by the agent but not registered in the registry"
                    )))?;
                }
            }

            // Resolve tool definitions from the registry.
            let tools: Vec<_> = agent
                .tool_names()
                .iter()
                .map(|name| runner.registry.get(name).unwrap().definition())
                .collect();

            let mut messages = history;
            let mut turn = 0u32;

            loop {
                turn += 1;
                debug!(turn, "calling model");

                let request = ModelRequest {
                    messages: messages.clone(),
                    system: Some(agent.instructions().to_string()),
                    output_schema: agent.output_schema().cloned(),
                    tools: tools.clone(),
                };

                let mut model_stream = std::pin::pin!(runner.model.generate_stream(request));
                let mut turn_tool_calls: Vec<ToolCall> = Vec::new();
                let mut has_text = false;

                while let Some(chunk) = model_stream.next().await {
                    match chunk? {
                        ModelStreamChunk::Thinking(t) => yield AgentEvent::Thinking(t),
                        ModelStreamChunk::TextDelta(t) => {
                            has_text = true;
                            yield AgentEvent::TextDelta(t);
                        }
                        ModelStreamChunk::ToolCall(call) => turn_tool_calls.push(call),
                    }
                }

                if turn_tool_calls.is_empty() {
                    if !has_text {
                        Err(Error::Agent(
                            "model returned neither text nor tool calls".to_string(),
                        ))?;
                    }
                    debug!("run complete");
                    break;
                }

                debug!(count = turn_tool_calls.len(), "model requested tool calls");

                // Append all tool calls as a single assistant turn.
                messages.push(Message::tool_calls(turn_tool_calls.clone()));

                // Emit ToolCallStarted for every call before any execute.
                for call in &turn_tool_calls {
                    debug!(tool = call.name, "executing tool");
                    yield AgentEvent::ToolCallStarted {
                        name: call.name.clone(),
                        args: call.args.clone(),
                    };
                }

                // Validate all tools exist and build their call futures.
                let mut tool_futures = Vec::new();
                for call in &turn_tool_calls {
                    let tool = runner.registry.get(&call.name).ok_or_else(|| {
                        Error::Agent(format!("model called unregistered tool '{}'", call.name))
                    })?;
                    tool_futures.push(tool.call(call.args.clone()));
                }

                // Execute all tool calls concurrently.
                let results = futures_util::future::join_all(tool_futures).await;

                // Emit ToolCallCompleted and append result messages in order.
                for (call, result) in turn_tool_calls.iter().zip(results) {
                    debug!(tool = call.name, "tool call complete");
                    let result = result?;
                    yield AgentEvent::ToolCallCompleted {
                        name: call.name.clone(),
                        result: result.clone(),
                    };
                    messages.push(Message::tool_result(
                        call.id.clone(),
                        call.name.clone(),
                        result,
                        call.provider_metadata.clone(),
                    ));
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::{ModelRequest, ModelResponse};
    use async_trait::async_trait;
    use serde::Deserialize;

    struct EchoModel;

    #[async_trait]
    impl LlmModel for EchoModel {
        async fn generate(&self, request: ModelRequest) -> Result<ModelResponse, Error> {
            let echo = request.messages.last().and_then(|m| {
                if let crate::model::MessageContent::Text(t) = &m.content {
                    Some(t.clone())
                } else {
                    None
                }
            });
            Ok(ModelResponse { text: echo, tool_calls: vec![], thinking: None })
        }
    }

    fn echo_runner() -> AgentRunner {
        AgentRunner::new(Box::new(EchoModel))
    }

    #[tokio::test]
    async fn run_returns_model_output() {
        let agent = Agent::builder()
            .name("Test")
            .instructions("Be helpful.")
            .build();

        let result = echo_runner().run(&agent, "hello").await.unwrap();
        assert_eq!(result.output, "hello");
    }

    #[derive(Debug, Deserialize, PartialEq)]
    struct Point {
        x: i32,
        y: i32,
    }

    struct JsonModel(String);

    #[async_trait]
    impl LlmModel for JsonModel {
        async fn generate(&self, _request: ModelRequest) -> Result<ModelResponse, Error> {
            Ok(ModelResponse { text: Some(self.0.clone()), tool_calls: vec![], thinking: None })
        }
    }

    #[tokio::test]
    async fn run_typed_deserializes_response() {
        let runner = AgentRunner::new(Box::new(JsonModel(r#"{"x":1,"y":2}"#.to_string())));
        let agent = Agent::builder()
            .name("Test")
            .instructions("Return a point.")
            .build();

        let point: Point = runner.run_typed(&agent, "give me a point").await.unwrap();
        assert_eq!(point, Point { x: 1, y: 2 });
    }

    #[tokio::test]
    async fn run_typed_returns_error_on_bad_json() {
        let runner = AgentRunner::new(Box::new(JsonModel("not json".to_string())));
        let agent = Agent::builder()
            .name("Test")
            .instructions("Return a point.")
            .build();

        let result: Result<Point, _> = runner.run_typed(&agent, "give me a point").await;
        assert!(matches!(result, Err(Error::Agent(_))));
    }

    #[tokio::test]
    async fn run_errors_when_tool_not_in_registry() {
        let agent = Agent::builder()
            .name("Test")
            .instructions("Use tools.")
            .tool("missing_tool")
            .build();

        let result = AgentRunner::new(Box::new(EchoModel)).run(&agent, "go").await;
        assert!(matches!(result, Err(Error::Agent(_))));
    }

    #[tokio::test]
    async fn run_executes_tool_loop_and_returns_text() {
        use crate::model::{MessageContent, ToolCall as ModelToolCall};
        use crate::tool::{Tool, ToolDefinition, ToolRegistry};
        use serde_json::json;
        use std::sync::atomic::{AtomicU32, Ordering};

        // Model: first call returns a tool call, second returns text.
        static CALL_COUNT: AtomicU32 = AtomicU32::new(0);

        struct ToolLoopModel;

        #[async_trait]
        impl LlmModel for ToolLoopModel {
            async fn generate(&self, request: ModelRequest) -> Result<ModelResponse, Error> {
                let n = CALL_COUNT.fetch_add(1, Ordering::SeqCst);
                if n == 0 {
                    Ok(ModelResponse {
                        text: None,
                        tool_calls: vec![ModelToolCall {
                            id: "call-1".to_string(),
                            name: "add".to_string(),
                            args: json!({"a": 1, "b": 2}),
                            provider_metadata: None,
                        }],
                        thinking: None,
                    })
                } else {
                    // The last message should be the tool result.
                    let last = request.messages.last().unwrap();
                    let answer = if let MessageContent::ToolResult { result, .. } = &last.content {
                        result["sum"].as_i64().unwrap_or(0).to_string()
                    } else {
                        "no result".to_string()
                    };
                    Ok(ModelResponse { text: Some(answer), tool_calls: vec![], thinking: None })
                }
            }
        }

        struct AddTool;

        #[async_trait]
        impl Tool for AddTool {
            fn definition(&self) -> ToolDefinition {
                ToolDefinition {
                    name: "add".to_string(),
                    description: "Adds two numbers.".to_string(),
                    parameters: json!({"type": "object"}),
                }
            }
            async fn call(&self, args: serde_json::Value) -> Result<serde_json::Value, Error> {
                let a = args["a"].as_i64().unwrap_or(0);
                let b = args["b"].as_i64().unwrap_or(0);
                Ok(json!({"sum": a + b}))
            }
        }

        CALL_COUNT.store(0, Ordering::SeqCst);
        let registry = Arc::new(ToolRegistry::new().register(Box::new(AddTool)));
        let runner = AgentRunner::with_registry(Box::new(ToolLoopModel), registry);
        let agent = Agent::builder()
            .name("Test")
            .instructions("Use tools.")
            .tool("add")
            .build();

        let result = runner.run(&agent, "add 1 and 2").await.unwrap();
        assert_eq!(result.output, "3");
    }

    // --- run_stream tests ---

    /// Collects all events from run_stream into a Vec for assertions.
    async fn collect_stream(runner: &AgentRunner, agent: &Agent, input: &str) -> Vec<AgentEvent> {
        let stream = runner.run_stream(agent, input);
        futures_util::pin_mut!(stream);
        let mut events = Vec::new();
        while let Some(event) = stream.next().await {
            events.push(event.expect("stream yielded an error"));
        }
        events
    }

    #[tokio::test]
    async fn run_stream_yields_text_delta() {
        let agent = Agent::builder().name("T").instructions("i").build();
        let events = collect_stream(&echo_runner(), &agent, "hello").await;
        assert_eq!(events.len(), 1);
        assert!(matches!(&events[0], AgentEvent::TextDelta(t) if t == "hello"));
    }

    #[tokio::test]
    async fn run_stream_yields_tool_call_events() {
        use crate::model::{MessageContent, ToolCall as ModelToolCall};
        use crate::tool::{Tool, ToolDefinition, ToolRegistry};
        use serde_json::json;
        use std::sync::atomic::{AtomicU32, Ordering};

        static CALL_COUNT2: AtomicU32 = AtomicU32::new(0);

        struct ToolLoopModel2;

        #[async_trait]
        impl LlmModel for ToolLoopModel2 {
            async fn generate(&self, request: ModelRequest) -> Result<ModelResponse, Error> {
                let n = CALL_COUNT2.fetch_add(1, Ordering::SeqCst);
                if n == 0 {
                    Ok(ModelResponse {
                        text: None,
                        tool_calls: vec![ModelToolCall {
                            id: "c1".to_string(),
                            name: "add".to_string(),
                            args: json!({"a": 3, "b": 4}),
                            provider_metadata: None,
                        }],
                        thinking: None,
                    })
                } else {
                    let last = request.messages.last().unwrap();
                    let answer =
                        if let MessageContent::ToolResult { result, .. } = &last.content {
                            result["sum"].as_i64().unwrap_or(0).to_string()
                        } else {
                            "no result".to_string()
                        };
                    Ok(ModelResponse { text: Some(answer), tool_calls: vec![], thinking: None })
                }
            }
        }

        struct AddTool2;

        #[async_trait]
        impl Tool for AddTool2 {
            fn definition(&self) -> ToolDefinition {
                ToolDefinition {
                    name: "add".to_string(),
                    description: "Adds.".to_string(),
                    parameters: serde_json::json!({"type": "object"}),
                }
            }
            async fn call(&self, args: serde_json::Value) -> Result<serde_json::Value, Error> {
                Ok(json!({"sum": args["a"].as_i64().unwrap_or(0) + args["b"].as_i64().unwrap_or(0)}))
            }
        }

        CALL_COUNT2.store(0, Ordering::SeqCst);
        let registry = Arc::new(ToolRegistry::new().register(Box::new(AddTool2)));
        let runner = AgentRunner::with_registry(Box::new(ToolLoopModel2), registry);
        let agent = Agent::builder().name("T").instructions("i").tool("add").build();

        let events = collect_stream(&runner, &agent, "go").await;

        // Expect: ToolCallStarted, ToolCallCompleted, TextDelta("7")
        assert_eq!(events.len(), 3);
        assert!(matches!(&events[0], AgentEvent::ToolCallStarted { name, .. } if name == "add"));
        assert!(matches!(&events[1], AgentEvent::ToolCallCompleted { name, .. } if name == "add"));
        assert!(matches!(&events[2], AgentEvent::TextDelta(t) if t == "7"));
    }

    #[tokio::test]
    async fn run_stream_executes_multiple_tool_calls_in_parallel() {
        use crate::model::{ToolCall as ModelToolCall};
        use crate::tool::{Tool, ToolDefinition, ToolRegistry};
        use serde_json::json;
        use std::sync::atomic::{AtomicU32, Ordering};

        static PARALLEL_CALL_COUNT: AtomicU32 = AtomicU32::new(0);

        // Model: first call returns two tool calls, second returns text.
        struct TwoToolModel;

        #[async_trait]
        impl LlmModel for TwoToolModel {
            async fn generate(&self, _request: ModelRequest) -> Result<ModelResponse, Error> {
                let n = PARALLEL_CALL_COUNT.fetch_add(1, Ordering::SeqCst);
                if n == 0 {
                    Ok(ModelResponse {
                        text: None,
                        tool_calls: vec![
                            ModelToolCall {
                                id: "c1".to_string(),
                                name: "double".to_string(),
                                args: json!({"x": 3}),
                                provider_metadata: None,
                            },
                            ModelToolCall {
                                id: "c2".to_string(),
                                name: "double".to_string(),
                                args: json!({"x": 7}),
                                provider_metadata: None,
                            },
                        ],
                        thinking: None,
                    })
                } else {
                    Ok(ModelResponse {
                        text: Some("done".to_string()),
                        tool_calls: vec![],
                        thinking: None,
                    })
                }
            }
        }

        struct DoubleTool;

        #[async_trait]
        impl Tool for DoubleTool {
            fn definition(&self) -> ToolDefinition {
                ToolDefinition {
                    name: "double".to_string(),
                    description: "Doubles a number.".to_string(),
                    parameters: json!({"type": "object"}),
                }
            }
            async fn call(&self, args: serde_json::Value) -> Result<serde_json::Value, Error> {
                let x = args["x"].as_i64().unwrap_or(0);
                Ok(json!({"result": x * 2}))
            }
        }

        PARALLEL_CALL_COUNT.store(0, Ordering::SeqCst);
        let registry = Arc::new(ToolRegistry::new().register(Box::new(DoubleTool)));
        let runner = AgentRunner::with_registry(Box::new(TwoToolModel), registry);
        let agent = Agent::builder()
            .name("T")
            .instructions("i")
            .tool("double")
            .build();

        let events = collect_stream(&runner, &agent, "go").await;

        // Expected: Started(c1), Started(c2), Completed(c1), Completed(c2), TextDelta
        assert_eq!(events.len(), 5);
        assert!(matches!(&events[0], AgentEvent::ToolCallStarted { name, args } if name == "double" && args["x"] == 3));
        assert!(matches!(&events[1], AgentEvent::ToolCallStarted { name, args } if name == "double" && args["x"] == 7));
        assert!(matches!(&events[2], AgentEvent::ToolCallCompleted { name, result } if name == "double" && result["result"] == 6));
        assert!(matches!(&events[3], AgentEvent::ToolCallCompleted { name, result } if name == "double" && result["result"] == 14));
        assert!(matches!(&events[4], AgentEvent::TextDelta(t) if t == "done"));
    }

    #[tokio::test]
    async fn run_stream_yields_thinking_events() {
        use futures_util::stream::Stream;
        use std::pin::Pin;

        struct ThinkingModel;

        #[async_trait]
        impl LlmModel for ThinkingModel {
            async fn generate(&self, _request: ModelRequest) -> Result<ModelResponse, Error> {
                Ok(ModelResponse { text: Some("answer".to_string()), tool_calls: vec![], thinking: None })
            }

            fn generate_stream(
                &self,
                _request: ModelRequest,
            ) -> Pin<Box<dyn Stream<Item = Result<ModelStreamChunk, Error>> + Send + '_>> {
                Box::pin(async_stream::stream! {
                    yield Ok(ModelStreamChunk::Thinking("hmm".to_string()));
                    yield Ok(ModelStreamChunk::TextDelta("answer".to_string()));
                })
            }
        }

        let runner = AgentRunner::new(Box::new(ThinkingModel));
        let agent = Agent::builder().name("T").instructions("i").build();
        let events = collect_stream(&runner, &agent, "q").await;

        assert_eq!(events.len(), 2);
        assert!(matches!(&events[0], AgentEvent::Thinking(t) if t == "hmm"));
        assert!(matches!(&events[1], AgentEvent::TextDelta(t) if t == "answer"));
    }

    #[tokio::test]
    async fn run_stream_propagates_error() {
        struct ErrorModel;

        #[async_trait]
        impl LlmModel for ErrorModel {
            async fn generate(&self, _request: ModelRequest) -> Result<ModelResponse, Error> {
                Err(Error::Provider("boom".to_string()))
            }
        }

        let runner = AgentRunner::new(Box::new(ErrorModel));
        let agent = Agent::builder().name("T").instructions("i").build();
        let stream = runner.run_stream(&agent, "q");
        futures_util::pin_mut!(stream);
        let first = stream.next().await.expect("stream should yield at least one item");
        assert!(matches!(first, Err(Error::Provider(_))));
    }

    #[tokio::test]
    async fn run_passes_system_instructions() {
        struct CaptureModel {
            captured: std::sync::Mutex<Option<ModelRequest>>,
        }

        #[async_trait]
        impl LlmModel for CaptureModel {
            async fn generate(&self, request: ModelRequest) -> Result<ModelResponse, Error> {
                *self.captured.lock().unwrap() = Some(request.clone());
                Ok(ModelResponse { text: Some(String::new()), tool_calls: vec![], thinking: None })
            }
        }

        let capture = std::sync::Arc::new(CaptureModel {
            captured: std::sync::Mutex::new(None),
        });

        struct ArcModel(std::sync::Arc<CaptureModel>);

        #[async_trait]
        impl LlmModel for ArcModel {
            async fn generate(&self, request: ModelRequest) -> Result<ModelResponse, Error> {
                self.0.generate(request).await
            }
        }

        let runner = AgentRunner::new(Box::new(ArcModel(capture.clone())));
        let agent = Agent::builder()
            .name("Test")
            .instructions("System prompt.")
            .build();

        runner.run(&agent, "input").await.unwrap();

        let req = capture.captured.lock().unwrap().clone().unwrap();
        assert_eq!(req.system.as_deref(), Some("System prompt."));
    }

    // --- RunBuilder / multi-turn tests ---

    /// A model that returns the full message list length as its response,
    /// letting tests inspect what history was passed in.
    struct MessageCountModel;

    #[async_trait]
    impl LlmModel for MessageCountModel {
        async fn generate(&self, request: ModelRequest) -> Result<ModelResponse, Error> {
            Ok(ModelResponse {
                text: Some(request.messages.len().to_string()),
                tool_calls: vec![],
                thinking: None,
            })
        }
    }

    #[tokio::test]
    async fn run_builder_without_history_passes_single_message() {
        let runner = AgentRunner::new(Box::new(MessageCountModel));
        let agent = Agent::builder().name("T").instructions("i").build();

        // No history → only the new user turn should be in the request.
        let result = runner.run_builder(&agent).run("hello").await.unwrap();
        assert_eq!(result.output, "1");
    }

    #[tokio::test]
    async fn run_builder_history_is_prepended_to_messages() {
        let runner = AgentRunner::new(Box::new(MessageCountModel));
        let agent = Agent::builder().name("T").instructions("i").build();

        let history = vec![
            Message::user("first turn"),
            Message::assistant("first reply"),
        ];

        // 2 history messages + 1 new user turn = 3 total.
        let result = runner
            .run_builder(&agent)
            .history(history)
            .run("second turn")
            .await
            .unwrap();
        assert_eq!(result.output, "3");
    }

    #[tokio::test]
    async fn run_builder_run_stream_with_history() {
        let runner = AgentRunner::new(Box::new(MessageCountModel));
        let agent = Agent::builder().name("T").instructions("i").build();

        let history = vec![Message::user("q1"), Message::assistant("a1")];

        let stream = runner.run_builder(&agent).history(history).run_stream("q2");
        futures_util::pin_mut!(stream);
        let mut text = String::new();
        while let Some(event) = stream.next().await {
            if let AgentEvent::TextDelta(chunk) = event.unwrap() {
                text.push_str(&chunk);
            }
        }
        // 2 history + 1 new = 3.
        assert_eq!(text, "3");
    }

    #[tokio::test]
    async fn run_builder_run_typed_with_history() {
        let runner = AgentRunner::new(Box::new(JsonModel(r#"{"x":5,"y":6}"#.to_string())));
        let agent = Agent::builder().name("T").instructions("i").build();

        let history = vec![Message::user("prev"), Message::assistant("ack")];

        let point: Point = runner
            .run_builder(&agent)
            .history(history)
            .run_typed("give me a point")
            .await
            .unwrap();
        assert_eq!(point, Point { x: 5, y: 6 });
    }
}